spring.application.name=HIVApp

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/uth_app
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

##config jwt
hivapp.jwt.secret=FoOU+4EWvObnBJ8UCnULlMk17lmsgtFcf+NVG+6eEIp8SJJKtxaiqrR+TnJVzfu96pvYMt5WL1+NecQZ22YlAg==
## Access token expiration (1 hour)
hivapp.jwt.token.expiration=3600
## Refresh token expiration (7 days)
hivapp.jwt.refresh-token.expiration=604800

# OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=1063022207771-c9qdp77hp484u9g1eag4judtn8m2a909.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email